### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by ye** [stefano-maggiolo/pydepgraph#1]
Currently `pydepgraph` runs great on `2.7.12` however, it is written in Python 2.x style that it won't install on Python 3.x let alone running it.

**Comment by johnyf** [comment]
Fixed in a fork (that may be merged back): https://github.com/johnyf/depg/tree/dev. The required changes were minimal, and are complete as of f070042bc9e1d75ae434612c31e3d13ab5294ffd.

**Comment by stefano-maggiolo** [comment]
Merged @ye's PR that arrived first. Thanks both!
