### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by arizhakov** [stefano-maggiolo/pydepgraph#3]
I tried to install this on my machine because the examples looked very promising and capability useful. But executing `setup.py` as instructed in your first paragraph of your tutorial [1], yields this error:

`Traceback (most recent call last):
  File "./setup.py", line 24, in <module>
    from builtins import (
`

Do you have any ideas on this? Is installation of this package seamless for others? I am running Python 2.7 on Ubuntu. Thanks!

[1] **http://blog.poormansmath.net/pydepgraph-a-dependencies-analyzer-for-python/**

**Comment by stefano-maggiolo** [comment]
I used the prescribed way of making the code py2 and 3 compatible, which I realized requires a fairly new version of Ubuntu (or installing some package manually). I reverted some of those changes, can you please try again?

FWIW, the code should still be 2 and 3 compatible.
